### ISSUE TITLE
Lesson 05 ui-params, why put 'bookmarks@' view in 'eggly.categories' state

### ISSUE THREAD

**Issue by LASkuma** [eggheadio/egghead-angularjs-eggly-architecture#5]
Since we already declared a 'bookmarks@' view inside of 'eggly.categories.bookmarks' state, what is the meaning for the one inside of 'eggy.categories' state?
BTW, the discussion panel seems broken on my machine. I cannot see the text frame for posting comments.

**Comment by ijones16** [comment]
This question seems to be answered in the [discussion tab on the video](https://egghead.io/lessons/angularjs-using-ui-router-s-named-views#/tab-discuss)
