### ISSUE TITLE
when  'catagories', 'catagories.bookmarks' as dependencies, it breaks

### ISSUE THREAD

**Issue by inaki** [eggheadio/egghead-angularjs-eggly-architecture#7]
Hello, I notice that when [ 'catagories', 'catagories.bookmarks'] are in the dependencies of eggly-app.js the app breaks, but is I don't put any dependencies in eggly-app.js it just works. Not sure why though!

**Comment by ijones16** [comment]
This issue is old. If you need any help still please open a new one. 

Cheers,

Ian
